import turtle
import time
import random
def go_up():
    print("W pressed")
    head.setheading(90)
def go_down():
    print("S pressed")
    head.setheading(270)
def go_left():
    print("D pressed")
    head.setheading(360)
def go_right():
    print("A pressed")
    head.setheading(540)    
s=turtle.Screen()  #画布
tails=[]           #设置一个数组存放尾巴


s.tracer(0)            #手动刷新屏幕

head=turtle.Turtle()   #蛇头
apple=turtle.Turtle()  #苹果
Goldenapple=turtle.Turtle()
Goldenapple1=turtle.Turtle()
Goldenapple2=turtle.Turtle()
Goldenapple3=turtle.Turtle()

s.update()
head.shape("square")
head.color("green")
head.penup()           #提起笔移动，不绘制图形
apple.shape("circle")
apple.color("red")
apple.penup()
apple.goto(100,100)
Goldenapple.shape("circle")
Goldenapple.color("yellow")
Goldenapple.penup()
Goldenapple.goto(100,100)
Goldenapple1.shape("circle")
Goldenapple1.color("yellow")
Goldenapple1.penup()
Goldenapple1.goto(100,100)
Goldenapple2.shape("circle")
Goldenapple2.color("yellow")
Goldenapple2.penup()
Goldenapple2.goto(100,100)
Goldenapple3.shape("circle")
Goldenapple3.color("yellow")
Goldenapple3.penup()
Goldenapple3.goto(100,100)

s.onkeypress(go_up,"W")
s.onkeypress(go_down,"S")
s.onkeypress(go_left,"D")
s.onkeypress(go_right,"A")
s.listen()
while True:
    if len(tails)>0:
        h_x=head.xcor()
        h_y=head.ycor()        #返回上一个坐标值（cor）
        tails[0].goto(h_x,h_y)
    for i in range(len(tails)-1,0,-1):   #获取每次尾巴长度，每次减一
        last_tail=tails[i-1]
        this_tail=tails[i]
        this_tail.goto(last_tail.xcor(),last_tail.ycor())
    head.forward(15)
    if head.distance(apple)<=20:
        new_x=random.randint(-300,300)
        new_y=random.randint(-300,300)
        apple.goto(new_x,new_y)
        tail=turtle.Turtle()
        tail.shape("circle")
        tail.color("green")
        tail.penup()
        tails.append(tail)     #tail存入tails数组
    if head.distance(Goldenapple)<=20:
        new_x=random.randint(-300,300)
        new_y=random.randint(-300,300)
        Goldenapple.goto(new_x,new_y)
        tail=turtle.Turtle()
        tail.shape("circle")
        tail.color("green")
        tail.penup()
        tails.append(tail)
        tail2=turtle.Turtle()
        tail2.shape("circle")
        tail2.color("green")
        tail2.penup()
        tails.append(tail2) 
        tail3=turtle.Turtle()
        tail3.shape("circle")
        tail3.color("green")
        tail3.penup()
        tails.append(tail3)
        tail4=turtle.Turtle()
        tail4.shape("circle")
        tail4.color("green")
        tail4.penup()
        tails.append(tail4)
        tail5=turtle.Turtle()
        tail5.shape("circle")
        tail5.color("green")
        tail5.penup()
        tails.append(tail5)
        tail6=turtle.Turtle()
        tail6.shape("circle")
        tail6.color("green")
        tail6.penup()
        tails.append(tail6)
        tail7=turtle.Turtle()
        tail7.shape("circle")
        tail7.color("green")
        tail7.penup()
        tails.append(tail7)
        tail8=turtle.Turtle()
        tail8.shape("circle")
        tail8.color("green")
        tail8.penup()
        tails.append(tail8)
        tail9=turtle.Turtle()
        tail9.shape("circle")
        tail9.color("green")
        tail9.penup()
        tails.append(tail9)
        tail0=turtle.Turtle()
        tail0.shape("circle")
        tail0.color("green")
        tail0.penup()
        tails.append(tail0)
    if head.distance(Goldenapple1)<=20:
        new_x=random.randint(-300,300)
        new_y=random.randint(-300,300)
        Goldenapple.goto(new_x,new_y)
        tail=turtle.Turtle()
        tail.shape("circle")
        tail.color("green")
        tail.penup()
        tails.append(tail)
        tail2=turtle.Turtle()
        tail2.shape("circle")
        tail2.color("green")
        tail2.penup()
        tails.append(tail2) 
        tail3=turtle.Turtle()
        tail3.shape("circle")
        tail3.color("green")
        tail3.penup()
        tails.append(tail3)
        tail4=turtle.Turtle()
        tail4.shape("circle")
        tail4.color("green")
        tail4.penup()
        tails.append(tail4)
        tail5=turtle.Turtle()
        tail5.shape("circle")
        tail5.color("green")
        tail5.penup()
        tails.append(tail5)
        tail6=turtle.Turtle()
        tail6.shape("circle")
        tail6.color("green")
        tail6.penup()
        tails.append(tail6)
        tail7=turtle.Turtle()
        tail7.shape("circle")
        tail7.color("green")
        tail7.penup()
        tails.append(tail7)
        tail8=turtle.Turtle()
        tail8.shape("circle")
        tail8.color("green")
        tail8.penup()
        tails.append(tail8)
        tail9=turtle.Turtle()
        tail9.shape("circle")
        tail9.color("green")
        tail9.penup()
        tails.append(tail9)
        tail0=turtle.Turtle()
        tail0.shape("circle")
        tail0.color("green")
        tail0.penup()
        tails.append(tail0)
    if head.distance(Goldenapple2)<=20:
        new_x=random.randint(-300,300)
        new_y=random.randint(-300,300)
        Goldenapple.goto(new_x,new_y)
        tail=turtle.Turtle()
        tail.shape("circle")
        tail.color("green")
        tail.penup()
        tails.append(tail)
        tail2=turtle.Turtle()
        tail2.shape("circle")
        tail2.color("green")
        tail2.penup()
        tails.append(tail2) 
        tail3=turtle.Turtle()
        tail3.shape("circle")
        tail3.color("green")
        tail3.penup()
        tails.append(tail3)
        tail4=turtle.Turtle()
        tail4.shape("circle")
        tail4.color("green")
        tail4.penup()
        tails.append(tail4)
        tail5=turtle.Turtle()
        tail5.shape("circle")
        tail5.color("green")
        tail5.penup()
        tails.append(tail5)
        tail6=turtle.Turtle()
        tail6.shape("circle")
        tail6.color("green")
        tail6.penup()
        tails.append(tail6)
        tail7=turtle.Turtle()
        tail7.shape("circle")
        tail7.color("green")
        tail7.penup()
        tails.append(tail7)
        tail8=turtle.Turtle()
        tail8.shape("circle")
        tail8.color("green")
        tail8.penup()
        tails.append(tail8)
        tail9=turtle.Turtle()
        tail9.shape("circle")
        tail9.color("green")
        tail9.penup()
        tails.append(tail9)
        tail0=turtle.Turtle()
        tail0.shape("circle")
        tail0.color("green")
        tail0.penup()
        tails.append(tail0)
    if head.distance(Goldenapple3)<=20:
        new_x=random.randint(-300,300)
        new_y=random.randint(-300,300)
        Goldenapple.goto(new_x,new_y)
        tail=turtle.Turtle()
        tail.shape("circle")
        tail.color("green")
        tail.penup()
        tails.append(tail)
        tail2=turtle.Turtle()
        tail2.shape("circle")
        tail2.color("green")
        tail2.penup()
        tails.append(tail2) 
        tail3=turtle.Turtle()
        tail3.shape("circle")
        tail3.color("green")
        tail3.penup()
        tails.append(tail3)
        tail4=turtle.Turtle()
        tail4.shape("circle")
        tail4.color("green")
        tail4.penup()
        tails.append(tail4)
        tail5=turtle.Turtle()
        tail5.shape("circle")
        tail5.color("green")
        tail5.penup()
        tails.append(tail5)
        tail6=turtle.Turtle()
        tail6.shape("circle")
        tail6.color("green")
        tail6.penup()
        tails.append(tail6)
        tail7=turtle.Turtle()
        tail7.shape("circle")
        tail7.color("green")
        tail7.penup()
        tails.append(tail7)
        tail8=turtle.Turtle()
        tail8.shape("circle")
        tail8.color("green")
        tail8.penup()
        tails.append(tail8)
        tail9=turtle.Turtle()
        tail9.shape("circle")
        tail9.color("green")
        tail9.penup()
        tails.append(tail9)
        tail0=turtle.Turtle()
        tail0.shape("circle")
        tail0.color("green")
        tail0.penup()
        tails.append(tail0)

    
    time.sleep(0.1)
    s.update()
s.mainloop()
